//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitMate.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitMate.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly-typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RevitMate.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RevitMate Assistant.
        /// </summary>
        public static string PanelTitle {
            get {
                return ResourceManager.GetString("PanelTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RevitMate Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RevitMate.
        /// </summary>
        public static string RibbonTabName {
            get {
                return ResourceManager.GetString("RibbonTabName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AI Tools.
        /// </summary>
        public static string RibbonPanelName {
            get {
                return ResourceManager.GetString("RibbonPanelName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open RevitMate.
        /// </summary>
        public static string OpenButtonText {
            get {
                return ResourceManager.GetString("OpenButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsButtonText {
            get {
                return ResourceManager.GetString("SettingsButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type a command or question....
        /// </summary>
        public static string InputPlaceholder {
            get {
                return ResourceManager.GetString("InputPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New conversation.
        /// </summary>
        public static string NewConversationButton {
            get {
                return ResourceManager.GetString("NewConversationButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyButton {
            get {
                return ResourceManager.GetString("CopyButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Executing:.
        /// </summary>
        public static string ExecutingPrefix {
            get {
                return ResourceManager.GetString("ExecutingPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tokens used:.
        /// </summary>
        public static string TokenUsageLabel {
            get {
                return ResourceManager.GetString("TokenUsageLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create a downlight grid in the selected room.
        /// </summary>
        public static string Suggestion1 {
            get {
                return ResourceManager.GetString("Suggestion1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Check circuit DB-L1 load.
        /// </summary>
        public static string Suggestion2 {
            get {
                return ResourceManager.GetString("Suggestion2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generate lighting schedule for this level.
        /// </summary>
        public static string Suggestion3 {
            get {
                return ResourceManager.GetString("Suggestion3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Claude API Key.
        /// </summary>
        public static string ApiKeyLabel {
            get {
                return ResourceManager.GetString("ApiKeyLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string ModelLabel {
            get {
                return ResourceManager.GetString("ModelLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max tokens per response.
        /// </summary>
        public static string MaxTokensLabel {
            get {
                return ResourceManager.GetString("MaxTokensLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AI response language.
        /// </summary>
        public static string ResponseLanguageLabel {
            get {
                return ResourceManager.GetString("ResponseLanguageLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto-detect from input.
        /// </summary>
        public static string LanguageAuto {
            get {
                return ResourceManager.GetString("LanguageAuto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string LanguageJapanese {
            get {
                return ResourceManager.GetString("LanguageJapanese", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid API key. Please update it in Settings..
        /// </summary>
        public static string ErrorInvalidApiKey {
            get {
                return ResourceManager.GetString("ErrorInvalidApiKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please open a Revit project first..
        /// </summary>
        public static string ErrorNoActiveDocument {
            get {
                return ResourceManager.GetString("ErrorNoActiveDocument", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network error. Check your internet connection..
        /// </summary>
        public static string ErrorNetworkFailure {
            get {
                return ResourceManager.GetString("ErrorNetworkFailure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {0}.
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thinking....
        /// </summary>
        public static string StatusThinking {
            get {
                return ResourceManager.GetString("StatusThinking", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Executing tool....
        /// </summary>
        public static string StatusExecuting {
            get {
                return ResourceManager.GetString("StatusExecuting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} element(s) selected.
        /// </summary>
        public static string SelectionStatus {
            get {
                return ResourceManager.GetString("SelectionStatus", resourceCulture);
            }
        }
    }
}
